name: 'Issue sync action'
description: 'Sync issues from one repository to another.'
branding:
  icon: repeat
  color: red
author: Maximisch
inputs:
  only_sync_on_label:
    description: 'If set, will only sync on issues with a label of this text'
    required: false
  repo_source:
    description: 'Org/Repo slug for the source repository. Will default to action launch repo if not set.'
    required: false
  repo_target:
    description: 'Org/repo slug for the target repository.'
    required: true
  only_sync_main_issue:
    description: 'Will exclude the syncing of comments.'
    required: false
    default: "false"
outputs:
  issue_id_target:
    description: 'The issue id of the found issue with the same name in the target repository, empty if not found'
  comment_id_target:
    description: 'The comment id of the created comment in the target repository, empty if not found'
runs:
  using: 'node16'
  main: 'dist/index.js'
