name: 'Issue sync action'
description: 'Sync issues from one repository to another.'
branding:
  icon: repeat
  color: red
author: Maximisch
inputs:
  only_sync_on_label:
    description: 'If set, will only sync on issues with a label of this text'
    required: false
  repo_source:
    description: 'Org/Repo slug for the source repository. Will default to action launch repo if not set.'
    required: false
  repo_target:
    description: 'Org/repo slug for the target repository.'
    required: true
  only_sync_main_issue:
    description: 'Will exclude the syncing of comments.'
    required: false
    default: "false"
runs:
  using: 'node16'
  main: 'dist/index.js'